# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Analyse.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AnalyseForm(object):
    def setupUi(self, AnalyseForm):
        AnalyseForm.setObjectName("AnalyseForm")
        AnalyseForm.resize(1200, 755)
        self.userNamelabel = QtWidgets.QLabel(AnalyseForm)
        self.userNamelabel.setGeometry(QtCore.QRect(1000, 10, 191, 41))
        self.userNamelabel.setStyleSheet("font: 9pt \"Consolas\" rgb(255, 14, 30);")
        self.userNamelabel.setObjectName("userNamelabel")
        self.goBackButton = QtWidgets.QPushButton(AnalyseForm)
        self.goBackButton.setGeometry(QtCore.QRect(1050, 700, 91, 41))
        self.goBackButton.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.goBackButton.setObjectName("goBackButton")
        self.zoomInButton = QtWidgets.QPushButton(AnalyseForm)
        self.zoomInButton.setGeometry(QtCore.QRect(140, 640, 91, 41))
        self.zoomInButton.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.zoomInButton.setObjectName("zoomInButton")
        self.zoomOutButton = QtWidgets.QPushButton(AnalyseForm)
        self.zoomOutButton.setGeometry(QtCore.QRect(490, 640, 91, 41))
        self.zoomOutButton.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.scoreTipsLabel = QtWidgets.QLabel(AnalyseForm)
        self.scoreTipsLabel.setGeometry(QtCore.QRect(780, 90, 101, 31))
        self.scoreTipsLabel.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.scoreTipsLabel.setObjectName("scoreTipsLabel")
        self.typeLabel = QtWidgets.QLabel(AnalyseForm)
        self.typeLabel.setGeometry(QtCore.QRect(780, 160, 101, 31))
        self.typeLabel.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.typeLabel.setObjectName("typeLabel")
        self.belongLabel = QtWidgets.QLabel(AnalyseForm)
        self.belongLabel.setGeometry(QtCore.QRect(780, 230, 101, 31))
        self.belongLabel.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.belongLabel.setObjectName("belongLabel")
        self.historyLineEdit = QtWidgets.QLineEdit(AnalyseForm)
        self.historyLineEdit.setGeometry(QtCore.QRect(910, 230, 141, 31))
        self.historyLineEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.historyLineEdit.setReadOnly(True)
        self.historyLineEdit.setObjectName("historyLineEdit")
        self.favoriteLineEdit = QtWidgets.QLineEdit(AnalyseForm)
        self.favoriteLineEdit.setGeometry(QtCore.QRect(910, 280, 141, 31))
        self.favoriteLineEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.favoriteLineEdit.setReadOnly(True)
        self.favoriteLineEdit.setObjectName("favoriteLineEdit")
        self.reciteLineEdit = QtWidgets.QLineEdit(AnalyseForm)
        self.reciteLineEdit.setGeometry(QtCore.QRect(910, 330, 141, 31))
        self.reciteLineEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.reciteLineEdit.setReadOnly(True)
        self.reciteLineEdit.setObjectName("reciteLineEdit")
        self.wrongLineEdit = QtWidgets.QLineEdit(AnalyseForm)
        self.wrongLineEdit.setGeometry(QtCore.QRect(910, 380, 141, 31))
        self.wrongLineEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.wrongLineEdit.setReadOnly(True)
        self.wrongLineEdit.setObjectName("wrongLineEdit")
        self.hishtoryCheckBox = QtWidgets.QCheckBox(AnalyseForm)
        self.hishtoryCheckBox.setGeometry(QtCore.QRect(1070, 230, 105, 22))
        self.hishtoryCheckBox.setText("")
        self.hishtoryCheckBox.setObjectName("hishtoryCheckBox")
        self.favoriteCheckBox = QtWidgets.QCheckBox(AnalyseForm)
        self.favoriteCheckBox.setGeometry(QtCore.QRect(1070, 280, 105, 22))
        self.favoriteCheckBox.setText("")
        self.favoriteCheckBox.setObjectName("favoriteCheckBox")
        self.reciteCheckBox = QtWidgets.QCheckBox(AnalyseForm)
        self.reciteCheckBox.setGeometry(QtCore.QRect(1070, 330, 105, 22))
        self.reciteCheckBox.setText("")
        self.reciteCheckBox.setObjectName("reciteCheckBox")
        self.wrongCheckBox = QtWidgets.QCheckBox(AnalyseForm)
        self.wrongCheckBox.setGeometry(QtCore.QRect(1070, 380, 105, 22))
        self.wrongCheckBox.setText("")
        self.wrongCheckBox.setObjectName("wrongCheckBox")
        self.typeLineEdit = QtWidgets.QLineEdit(AnalyseForm)
        self.typeLineEdit.setGeometry(QtCore.QRect(910, 160, 91, 31))
        self.typeLineEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.typeLineEdit.setReadOnly(True)
        self.typeLineEdit.setObjectName("typeLineEdit")
        self.scoreLineEdit = QtWidgets.QLineEdit(AnalyseForm)
        self.scoreLineEdit.setGeometry(QtCore.QRect(910, 90, 61, 31))
        self.scoreLineEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.scoreLineEdit.setReadOnly(True)
        self.scoreLineEdit.setObjectName("scoreLineEdit")
        self.totScoreLabel = QtWidgets.QLabel(AnalyseForm)
        self.totScoreLabel.setGeometry(QtCore.QRect(970, 90, 81, 31))
        self.totScoreLabel.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.totScoreLabel.setObjectName("totScoreLabel")
        self.sourceLabel = QtWidgets.QLabel(AnalyseForm)
        self.sourceLabel.setGeometry(QtCore.QRect(780, 440, 101, 31))
        self.sourceLabel.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.sourceLabel.setObjectName("sourceLabel")
        self.sourceLineEdit = QtWidgets.QLineEdit(AnalyseForm)
        self.sourceLineEdit.setGeometry(QtCore.QRect(910, 440, 141, 31))
        self.sourceLineEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.sourceLineEdit.setReadOnly(True)
        self.sourceLineEdit.setObjectName("sourceLineEdit")
        self.timesLabel = QtWidgets.QLabel(AnalyseForm)
        self.timesLabel.setGeometry(QtCore.QRect(780, 520, 141, 31))
        self.timesLabel.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.timesLabel.setObjectName("timesLabel")
        self.timesLineEdit = QtWidgets.QLineEdit(AnalyseForm)
        self.timesLineEdit.setGeometry(QtCore.QRect(910, 520, 41, 31))
        self.timesLineEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.timesLineEdit.setReadOnly(True)
        self.timesLineEdit.setObjectName("timesLineEdit")
        self.memoryLabel = QtWidgets.QLabel(AnalyseForm)
        self.memoryLabel.setGeometry(QtCore.QRect(780, 600, 141, 31))
        self.memoryLabel.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.memoryLabel.setObjectName("memoryLabel")
        self.memoryLineEdit = QtWidgets.QLineEdit(AnalyseForm)
        self.memoryLineEdit.setGeometry(QtCore.QRect(910, 600, 141, 31))
        self.memoryLineEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.memoryLineEdit.setReadOnly(True)
        self.memoryLineEdit.setObjectName("memoryLineEdit")
        self.timesLabel_2 = QtWidgets.QLabel(AnalyseForm)
        self.timesLabel_2.setGeometry(QtCore.QRect(980, 520, 141, 31))
        self.timesLabel_2.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.timesLabel_2.setObjectName("timesLabel_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(AnalyseForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 661, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(AnalyseForm)
        self.scrollArea.setGeometry(QtCore.QRect(49, 40, 661, 561))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        '''
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 559))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        '''
        self.label = QtWidgets.QLabel()
        self.label.setGeometry(QtCore.QRect(0, 0, 661, 561))
        self.label.setText("")
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.label)

        self.retranslateUi(AnalyseForm)
        QtCore.QMetaObject.connectSlotsByName(AnalyseForm)

    def retranslateUi(self, AnalyseForm):
        _translate = QtCore.QCoreApplication.translate
        AnalyseForm.setWindowTitle(_translate("AnalyseForm", "小航搜题-历史答案分析"))
        self.userNamelabel.setText(_translate("AnalyseForm", "用户名：蛤蛤蛤蛤蛤蛤"))
        self.goBackButton.setText(_translate("AnalyseForm", "返回"))
        self.zoomInButton.setText(_translate("AnalyseForm", "缩小"))
        self.zoomOutButton.setText(_translate("AnalyseForm", "放大"))
        self.scoreTipsLabel.setText(_translate("AnalyseForm", "此次分数："))
        self.typeLabel.setText(_translate("AnalyseForm", "题目类型："))
        self.belongLabel.setText(_translate("AnalyseForm", "题目所属："))
        self.historyLineEdit.setText(_translate("AnalyseForm", "我的历史记录"))
        self.favoriteLineEdit.setText(_translate("AnalyseForm", "我喜欢的问题"))
        self.reciteLineEdit.setText(_translate("AnalyseForm", "我的背题集"))
        self.wrongLineEdit.setText(_translate("AnalyseForm", "我的错题本"))
        self.typeLineEdit.setText(_translate("AnalyseForm", "暂无"))
        self.scoreLineEdit.setText(_translate("AnalyseForm", "暂无"))
        self.totScoreLabel.setText(_translate("AnalyseForm", "/10"))
        self.sourceLabel.setText(_translate("AnalyseForm", "题目来源："))
        self.sourceLineEdit.setText(_translate("AnalyseForm", "原始题库"))
        self.timesLabel.setText(_translate("AnalyseForm", "当前是第："))
        self.timesLineEdit.setText(_translate("AnalyseForm", "0"))
        self.memoryLabel.setText(_translate("AnalyseForm", "记录原因："))
        self.memoryLineEdit.setText(_translate("AnalyseForm", "搜索题目"))
        self.timesLabel_2.setText(_translate("AnalyseForm", "次完成"))

