# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ObjectiveItemQuiz.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ObjectiveItemQuizForm(object):
    def setupUi(self, ObjectiveItemQuizForm):
        ObjectiveItemQuizForm.setObjectName("ObjectiveItemQuizForm")
        ObjectiveItemQuizForm.resize(1200, 755)
        self.choiceQuestionTextEdit = QtWidgets.QTextEdit(ObjectiveItemQuizForm)
        self.choiceQuestionTextEdit.setGeometry(QtCore.QRect(240, 60, 821, 141))
        self.choiceQuestionTextEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.choiceQuestionTextEdit.setObjectName("choiceQuestionTextEdit")
        self.preQuestionButton = QtWidgets.QPushButton(ObjectiveItemQuizForm)
        self.preQuestionButton.setGeometry(QtCore.QRect(30, 210, 151, 51))
        self.preQuestionButton.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.preQuestionButton.setObjectName("preQuestionButton")
        self.clearButton = QtWidgets.QPushButton(ObjectiveItemQuizForm)
        self.clearButton.setGeometry(QtCore.QRect(30, 60, 151, 51))
        self.clearButton.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.clearButton.setObjectName("clearButton")
        self.nextQuestionButton = QtWidgets.QPushButton(ObjectiveItemQuizForm)
        self.nextQuestionButton.setGeometry(QtCore.QRect(30, 390, 151, 51))
        self.nextQuestionButton.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.nextQuestionButton.setObjectName("nextQuestionButton")
        self.userNamelabel = QtWidgets.QLabel(ObjectiveItemQuizForm)
        self.userNamelabel.setGeometry(QtCore.QRect(1000, 10, 191, 41))
        self.userNamelabel.setStyleSheet("font: 9pt \"Consolas\" rgb(255, 14, 30);")
        self.userNamelabel.setObjectName("userNamelabel")
        self.scheduleLabel = QtWidgets.QLabel(ObjectiveItemQuizForm)
        self.scheduleLabel.setGeometry(QtCore.QRect(510, 30, 301, 31))
        self.scheduleLabel.setStyleSheet("font: 9pt \"Consolas\" rgb(255, 14, 30);")
        self.scheduleLabel.setObjectName("scheduleLabel")
        self.confirmButton = QtWidgets.QPushButton(ObjectiveItemQuizForm)
        self.confirmButton.setGeometry(QtCore.QRect(550, 610, 151, 51))
        self.confirmButton.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.confirmButton.setObjectName("confirmButton")
        self.goBackButton = QtWidgets.QPushButton(ObjectiveItemQuizForm)
        self.goBackButton.setGeometry(QtCore.QRect(1050, 700, 91, 41))
        self.goBackButton.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.goBackButton.setObjectName("goBackButton")
        self.AQuestionTextEdit = QtWidgets.QTextEdit(ObjectiveItemQuizForm)
        self.AQuestionTextEdit.setGeometry(QtCore.QRect(310, 220, 751, 71))
        self.AQuestionTextEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.AQuestionTextEdit.setObjectName("AQuestionTextEdit")
        self.BQuestionTextEdit = QtWidgets.QTextEdit(ObjectiveItemQuizForm)
        self.BQuestionTextEdit.setGeometry(QtCore.QRect(310, 310, 751, 71))
        self.BQuestionTextEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.BQuestionTextEdit.setObjectName("BQuestionTextEdit")
        self.CQuestionTextEdit = QtWidgets.QTextEdit(ObjectiveItemQuizForm)
        self.CQuestionTextEdit.setGeometry(QtCore.QRect(310, 400, 751, 71))
        self.CQuestionTextEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.CQuestionTextEdit.setObjectName("CQuestionTextEdit")
        self.DQuestionTextEdit = QtWidgets.QTextEdit(ObjectiveItemQuizForm)
        self.DQuestionTextEdit.setGeometry(QtCore.QRect(310, 490, 751, 71))
        self.DQuestionTextEdit.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.DQuestionTextEdit.setObjectName("DQuestionTextEdit")
        self.AradioButton = QtWidgets.QRadioButton(ObjectiveItemQuizForm)
        self.AradioButton.setGeometry(QtCore.QRect(260, 230, 31, 41))
        self.AradioButton.setText("")
        self.AradioButton.setObjectName("AradioButton")
        self.BradioButton = QtWidgets.QRadioButton(ObjectiveItemQuizForm)
        self.BradioButton.setGeometry(QtCore.QRect(260, 320, 31, 41))
        self.BradioButton.setText("")
        self.BradioButton.setObjectName("BradioButton")
        self.CradioButton = QtWidgets.QRadioButton(ObjectiveItemQuizForm)
        self.CradioButton.setGeometry(QtCore.QRect(260, 410, 31, 41))
        self.CradioButton.setText("")
        self.CradioButton.setObjectName("CradioButton")
        self.DradioButton = QtWidgets.QRadioButton(ObjectiveItemQuizForm)
        self.DradioButton.setGeometry(QtCore.QRect(260, 500, 31, 41))
        self.DradioButton.setText("")
        self.DradioButton.setObjectName("DradioButton")
        self.scoreLabel = QtWidgets.QLabel(ObjectiveItemQuizForm)
        self.scoreLabel.setGeometry(QtCore.QRect(960, 600, 131, 41))
        self.scoreLabel.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.scoreLabel.setObjectName("scoreLabel")
        self.answerLabel = QtWidgets.QLabel(ObjectiveItemQuizForm)
        self.answerLabel.setGeometry(QtCore.QRect(550, 680, 251, 41))
        self.answerLabel.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.answerLabel.setObjectName("answerLabel")

        self.retranslateUi(ObjectiveItemQuizForm)
        QtCore.QMetaObject.connectSlotsByName(ObjectiveItemQuizForm)

    def retranslateUi(self, ObjectiveItemQuizForm):
        _translate = QtCore.QCoreApplication.translate
        ObjectiveItemQuizForm.setWindowTitle(_translate("ObjectiveItemQuizForm", "小航搜题-小测试"))
        self.preQuestionButton.setText(_translate("ObjectiveItemQuizForm", "上一题"))
        self.clearButton.setText(_translate("ObjectiveItemQuizForm", "清空答题区"))
        self.nextQuestionButton.setText(_translate("ObjectiveItemQuizForm", "下一题"))
        self.userNamelabel.setText(_translate("ObjectiveItemQuizForm", "用户名：蛤蛤蛤蛤蛤蛤"))
        self.scheduleLabel.setText(_translate("ObjectiveItemQuizForm", "正在识别文件，请耐心等待。。。"))
        self.confirmButton.setText(_translate("ObjectiveItemQuizForm", "确认提交"))
        self.goBackButton.setText(_translate("ObjectiveItemQuizForm", "返回"))
        self.scoreLabel.setText(_translate("ObjectiveItemQuizForm", "得分：10/10"))
        self.answerLabel.setText(_translate("ObjectiveItemQuizForm", "正确答案：A, B, C, D"))

